services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6-alpine

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/usr/src/app
      - ./templates:/usr/src/app/templates 
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
    - PYTHONPATH=/usr/src
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    environment:
    - PYTHONPATH=/usr/src
    depends_on:
      api:
        condition: service_started

  scheduler:
    build: .
    command: celery -A app.worker.celery_app beat --loglevel=info
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    environment:
    - PYTHONPATH=/usr/src
    depends_on:
      api:
        condition: service_started

volumes:
  postgres_data: